# Generated by Django 4.2.5 on 2023-10-04 15:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_driveruser_account_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('document_image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modification_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.driveruser')),
            ],
        ),
        migrations.CreateModel(
            name='CargoDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('document_type', models.CharField(choices=[('t1_document', 'T1 Document'), ('c2_document', 'C2 Document'), ('cargo_declaration', 'Cargo Declaration')], max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('cargo_tones', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'Cargo Document',
                'verbose_name_plural': 'Cargo Documents',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('health_certificate', 'Health Certificate')], max_length=50)),
            ],
            options={
                'verbose_name': 'Personal Document',
                'verbose_name_plural': 'Personal Documents',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='TruckDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance'), ('transit goods documents', 'Certified Tansit Goods Document')], max_length=50)),
            ],
            options={
                'verbose_name': 'Truck Document',
                'verbose_name_plural': 'Truck Documents',
            },
            bases=('documents.document',),
        ),
    ]
